name: hw-diagnostics
version: '0.0.0.7'
synopsis: Diagnostics library
description: Please see README.md
category: Profiling
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-diagnostics
homepage: http://github.com/haskell-works/hw-diagnostics#readme
extra-source-files:
- README.md
dependencies:
- base >=4 && <5
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - HaskellWorks.Diagnostics
  - HaskellWorks.Diagnostics.Time
